name: Deploy to Hostinger Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Hostinger Env

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build project (if needed)
        run: npm run build

      - name: Print ssh
        run: |
          echo "$SSH_PRIVATE_KEY" >> secrets.txt
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} 
      
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            cd /home/projects/my-portfolio
            git pull origin main
            docker-compose down
            docker-compose up --build -d
